# Importing Libraries

In [1]:
#import all the necessary libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# Importing the Dataset

In [2]:
#import the dataset

dataset = pd.read_csv('C:\\Users\\Chandu\\Desktop\\Datasets\\SAT-GPA.csv')

# Observing the Dataset

In [3]:
#observe the dataset

dataset

SAT   GPA
0   1714  2.40
1   1664  2.52
2   1760  2.54
3   1685  2.74
4   1693  2.83
..   ...   ...
79  1936  3.71
80  1810  3.71
81  1987  3.73
82  1962  3.76
83  2050  3.81

[84 rows x 2 columns]

This dataset gives us the information about the SAT scores and GPA.
By using the simple linear regression, let's predict the SAT score based on the GPA.

# Preprocessing the Dataset

In [4]:
#Getting the basic information of the dataset

dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   SAT     84 non-null     int64  
 1   GPA     84 non-null     float64
dtypes: float64(1), int64(1)
memory usage: 1.4 KB


This dataset has 84 entries of SAT and GPA values of which SAT is of integer and GPA is of float datatype.

In [5]:
#Let's seperately check for only null values

dataset.isnull().sum()

SAT    0
GPA    0
dtype: int64

This tells us that none of the columns in the dataset has null values.

# Visualizing the Data

In [6]:
#Lets draw a graph between SAT and GPA scores

plt.figure(figsize=(40,20))
plt.plot(dataset["GPA"], dataset["SAT"])
plt.xlabel('GPA')
plt.ylabel('SAT')
plt.show()


# Dividing into input and output

Since, the students having higher GPA will probably have a higher SAT score, let's take the GPA as the independent factor(x) and the SAT score as the dependent factor(y)

In [7]:
#Let's take the GPA as 'x-values'(input) and SAT scores as 'y-values'(output).

x = dataset["GPA"].values
y = dataset["SAT"].values

In [8]:
#Let's see the shape of x

x.shape

(84,)

Since our x(input) values should be a 2-D array, let us reshape this 1-D array into a 2-D array.

In [9]:
#Let's reshape x

x = x.reshape(84,1)
x.shape

(84, 1)

In [12]:
#Let's see the x values
x

array([[2.4 ],
       [2.52],
       [2.54],
       [2.74],
       [2.83],
       [2.91],
       [3.  ],
       [3.  ],
       [3.01],
       [3.01],
       [3.02],
       [3.07],
       [3.08],
       [3.08],
       [3.12],
       [3.17],
       [3.17],
       [3.17],
       [3.17],
       [3.19],
       [3.19],
       [3.19],
       [3.2 ],
       [3.21],
       [3.24],
       [3.28],
       [3.28],
       [3.28],
       [3.28],
       [3.28],
       [3.28],
       [3.28],
       [3.29],
       [3.29],
       [3.29],
       [3.31],
       [3.32],
       [3.34],
       [3.37],
       [3.37],
       [3.37],
       [3.38],
       [3.38],
       [3.39],
       [3.39],
       [3.4 ],
       [3.4 ],
       [3.4 ],
       [3.41],
       [3.41],
       [3.41],
       [3.42],
       [3.42],
       [3.42],
       [3.44],
       [3.47],
       [3.47],
       [3.47],
       [3.47],
       [3.48],
       [3.49],
       [3.49],
       [3.5 ],
       [3.51],
       [3.51],
       [3.52],
       [3.

In [13]:
#Let's see the y values

y

array([1714, 1664, 1760, 1685, 1693, 1670, 1764, 1764, 1792, 1850, 1735,
       1775, 1735, 1712, 1773, 1872, 1755, 1674, 1842, 1786, 1761, 1722,
       1663, 1687, 1974, 1826, 1787, 1821, 2020, 1794, 1769, 1934, 1775,
       1855, 1880, 1849, 1808, 1954, 1777, 1831, 1865, 1850, 1966, 1702,
       1990, 1925, 1824, 1956, 1857, 1979, 1802, 1855, 1907, 1634, 1879,
       1887, 1730, 1953, 1781, 1891, 1964, 1808, 1893, 2041, 1893, 1832,
       1850, 1934, 1861, 1931, 1933, 1778, 1975, 1934, 2021, 2015, 1997,
       2020, 1843, 1936, 1810, 1987, 1962, 2050], dtype=int64)

In [14]:
#Let's see the shape of y

y.shape

(84,)

# Dividing the dataset into Train and Test parts

In [15]:
#Let's split the dataset into testing and training part

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [16]:
#Let's see the size of x_train and y_train dataparts

x_train.size, y_train.size

(67, 67)

In [17]:
#Let's see the shape of x_train and y_train dataparts

x_train.shape, y_train.shape

((67, 1), (67,))

In [18]:
#Let's see the size of x_test and y_test dataparts

x_test.size, y_test.size

(17, 17)

# Running a Regressor

In [19]:
#Let's run a regressor to get the predicted values of GPA based on the SAT scores.

lr = LinearRegression()

# Fitting the model

In [20]:
#Let's fit the model by mapping the input with output of the training dataset.

lr = lr.fit(x_train, y_train)

# Predicting the output

In [21]:
#Let's predict the output values(y_test) based on the input values(x_test)

y_pred = lr.predict(x_test)
y_pred

array([1848.07614057, 1825.54973684, 1757.97052562, 1815.53800184,
       1825.54973684, 1605.29156696, 1933.17588803, 1775.49106186,
       1958.20522551, 1918.15828554, 1825.54973684, 1860.59080932,
       1853.08200807, 1755.46759188, 1908.14655054, 1803.0233331 ,
       1825.54973684])

In [22]:
#Let's see the actual output values(y_test)

y_test

array([1777, 2020, 1792, 1974, 1794, 1714, 1843, 1712, 2050, 2020, 1821,
       1855, 1990, 1764, 2021, 1722, 1826], dtype=int64)

In [23]:
#Let's see the difference between the actual and the predicted output values

y_test - y_pred

array([-71.07614057, 194.45026316,  34.02947438, 158.46199816,
       -31.54973684, 108.70843304, -90.17588803, -63.49106186,
        91.79477449, 101.84171446,  -4.54973684,  -5.59080932,
       136.91799193,   8.53240812, 112.85344946, -81.0233331 ,
         0.45026316])

In [24]:
#Let's see the graphical representation of the actual and the predicted output values

#let's point the actual output values(y_test) vs the actual input values(x_test)
plt.scatter(x_test, y_test)

#let's point the predicted output values(y_pred) vs the actual input values(x_test)
plt.plot(x_test, y_pred, 'r')

# Evaluating the Accuracy score of the model

In [25]:
#Let's check the accuracy score of the model

r2_score(y_test, y_pred)

0.35195230536922706

In [26]:
import  statsmodels.api as sm

In [27]:
model = sm.OLS(y_train,x_train).fit()
predictions = model.predict(x_train)

model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.997
Model:                            OLS   Adj. R-squared (uncentered):              0.996
Method:                 Least Squares   F-statistic:                          1.906e+04
Date:                Thu, 01 Sep 2022   Prob (F-statistic):                    5.54e-83
Time:                        20:35:47   Log-Likelihood:                         -408.94
No. Observations:                  67   AIC:                                      819.9
Df Residuals:                      66   BIC:                                      822.1
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           549.3717      3.979    138.055      0.000     541.427     557.317
==============================================================================
Omnibus:                        5.582   Durbin-Watson:                   2.109
Prob(Omnibus):                  0.061   Jarque-Bera (JB):                5.474
Skew:                           0.405   Prob(JB):                       0.0648
Kurtosis:                       4.142   Cond. No.                         1.00
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [28]:
model = sm.OLS(y_test,x_test).fit()
predictions = model.predict(x_test)

model.summary()

C:\Users\Chandu\anaconda3\lib\site-packages\scipy\stats\stats.py:1603: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.995
Model:                            OLS   Adj. R-squared (uncentered):              0.995
Method:                 Least Squares   F-statistic:                              3087.
Date:                Thu, 01 Sep 2022   Prob (F-statistic):                    9.83e-20
Time:                        20:35:47   Log-Likelihood:                         -107.40
No. Observations:                  17   AIC:                                      216.8
Df Residuals:                      16   BIC:                                      217.6
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           563.0097     10.133     55.561      0.000     541.528     584.491
==============================================================================
Omnibus:                        4.694   Durbin-Watson:                   2.540
Prob(Omnibus):                  0.096   Jarque-Bera (JB):                2.264
Skew:                           0.757   Prob(JB):                        0.322
Kurtosis:                       3.951   Cond. No.                         1.00
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""